//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::people::Entity as People;
pub use super::universities::Entity as Universities;
pub use super::university_people::Entity as UniversityPeople;
pub use super::users::Entity as Users;
