//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "universities")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub icon: String,
    #[sea_orm(column_type = "Float")]
    pub lon: f32,
    #[sea_orm(column_type = "Float")]
    pub lat: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::university_people::Entity")]
    UniversityPeople,
}

impl Related<super::university_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UniversityPeople.def()
    }
}
