//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "university_people")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub university_id: i32,
    pub people_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::people::Entity",
        from = "Column::PeopleId",
        to = "super::people::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    People,
    #[sea_orm(
        belongs_to = "super::universities::Entity",
        from = "Column::UniversityId",
        to = "super::universities::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Universities,
}

impl Related<super::people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::People.def()
    }
}

impl Related<super::universities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Universities.def()
    }
}
