[package]
name = "entity"
version = "1.1.0"
authors = ["ckgxrg <ckgxrg@gmail.com>"]
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.11" }
serde = { version = "1.0.219", features = ["derive"] }
