//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "profile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name_primary: String,
    pub name_supplementary: Option<String>,
    pub avatar: String,
    pub class_of: i32,
    pub university_id: i32,
    pub major: Option<String>,
    pub bio: Option<String>,
    pub email: Option<String>,
    pub qq: Option<String>,
    pub wechat: Option<String>,
    pub matrix: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::university::Entity",
        from = "Column::UniversityId",
        to = "super::university::Column::Id"
    )]
    University,
}

impl ActiveModelBehavior for ActiveModel {}
